const projectJson = {
  targets: [
    {
      isStage: true,
      name: "Stage",
      variables: {
        "Omb^c,YW;.!Uj1A7~oJ1": ["player x", 0],
        "e[7yT@wnA!3^S:!PNY~Q": ["player y", 0],
        "+qm~UdN|JU.$.!V$*+Ka": ["camera x", 0],
        ";sLdt+zV]./UgHiZH2)+": ["camera y", 0],
        "$/yw+8k;*81pDO7cl%%P": ["speed x", 0],
        "pT.e}n4RtL+`ZAiT$cnI": ["speed y", 0],
      },
      lists: { "/]:RR9WxA|~;a{XK,{rv": ["world data", []] },
      broadcasts: {},
      blocks: {},
      comments: {},
      currentCostume: 0,
      costumes: [
        {
          name: "background",
          dataFormat: "svg",
          assetId: "cd21514d0531fdffb22204e0ec5ed84a",
          md5ext: "cd21514d0531fdffb22204e0ec5ed84a.svg",
          rotationCenterX: 240,
          rotationCenterY: 180,
        },
      ],
      sounds: [],
      volume: 100,
      layerOrder: 0,
      tempo: 60,
      videoTransparency: 50,
      videoState: "on",
      textToSpeechLanguage: "ja",
    },
    {
      isStage: false,
      name: "player",
      variables: {},
      lists: {},
      broadcasts: {},
      blocks: {
        bv: {
          opcode: "event_whenflagclicked",
          next: "X",
          parent: null,
          inputs: {},
          fields: {},
          shadow: false,
          topLevel: true,
          x: 48,
          y: 64,
        },
        X: {
          opcode: "data_setvariableto",
          next: "Y",
          parent: "bv",
          inputs: { VALUE: [1, [10, "0"]] },
          fields: { VARIABLE: ["player x", "Omb^c,YW;.!Uj1A7~oJ1"] },
          shadow: false,
          topLevel: false,
        },
        Y: {
          opcode: "data_setvariableto",
          next: "Z",
          parent: "X",
          inputs: { VALUE: [1, [10, "0"]] },
          fields: { VARIABLE: ["player y", "e[7yT@wnA!3^S:!PNY~Q"] },
          shadow: false,
          topLevel: false,
        },
        Z: {
          opcode: "data_setvariableto",
          next: "!",
          parent: "Y",
          inputs: { VALUE: [1, [10, "0"]] },
          fields: { VARIABLE: ["speed x", "$/yw+8k;*81pDO7cl%%P"] },
          shadow: false,
          topLevel: false,
        },
        "!": {
          opcode: "data_setvariableto",
          next: "#",
          parent: "Z",
          inputs: { VALUE: [1, [10, "0"]] },
          fields: { VARIABLE: ["speed y", "pT.e}n4RtL+`ZAiT$cnI"] },
          shadow: false,
          topLevel: false,
        },
        "#": {
          opcode: "control_forever",
          next: null,
          parent: "!",
          inputs: { SUBSTACK: [2, "a"] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        a: {
          opcode: "control_if",
          next: "b",
          parent: "#",
          inputs: { CONDITION: [2, "%"], SUBSTACK: [2, "bw"] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        "%": {
          opcode: "sensing_keypressed",
          next: null,
          parent: "a",
          inputs: { KEY_OPTION: [1, "bx"] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        bx: {
          opcode: "sensing_keyoptions",
          next: null,
          parent: "%",
          inputs: {},
          fields: { KEY_OPTION: ["right arrow", null] },
          shadow: true,
          topLevel: false,
        },
        bw: {
          opcode: "data_changevariableby",
          next: null,
          parent: "a",
          inputs: { VALUE: [1, [4, "3"]] },
          fields: { VARIABLE: ["speed x", "$/yw+8k;*81pDO7cl%%P"] },
          shadow: false,
          topLevel: false,
        },
        b: {
          opcode: "control_if",
          next: "v",
          parent: "a",
          inputs: { CONDITION: [2, "("], SUBSTACK: [2, "by"] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        "(": {
          opcode: "sensing_keypressed",
          next: null,
          parent: "b",
          inputs: { KEY_OPTION: [1, "bz"] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        bz: {
          opcode: "sensing_keyoptions",
          next: null,
          parent: "(",
          inputs: {},
          fields: { KEY_OPTION: ["left arrow", null] },
          shadow: true,
          topLevel: false,
        },
        by: {
          opcode: "data_changevariableby",
          next: null,
          parent: "b",
          inputs: { VALUE: [1, [4, "-3"]] },
          fields: { VARIABLE: ["speed x", "$/yw+8k;*81pDO7cl%%P"] },
          shadow: false,
          topLevel: false,
        },
        v: {
          opcode: "data_setvariableto",
          next: ")",
          parent: "b",
          inputs: { VALUE: [3, "bA", [10, ""]] },
          fields: { VARIABLE: ["speed x", "$/yw+8k;*81pDO7cl%%P"] },
          shadow: false,
          topLevel: false,
        },
        bA: {
          opcode: "operator_multiply",
          next: null,
          parent: "v",
          inputs: {
            NUM1: [3, [12, "speed x", "$/yw+8k;*81pDO7cl%%P"], [4, ""]],
            NUM2: [1, [4, "0.8"]],
          },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        ")": {
          opcode: "procedures_call",
          next: "*",
          parent: "v",
          inputs: {},
          fields: {},
          shadow: false,
          topLevel: false,
          mutation: {
            tagName: "mutation",
            children: [],
            proccode: "move x",
            argumentids: "[]",
            warp: "true",
          },
        },
        "*": {
          opcode: "data_changevariableby",
          next: "c",
          parent: ")",
          inputs: { VALUE: [1, [4, "-2"]] },
          fields: { VARIABLE: ["speed y", "pT.e}n4RtL+`ZAiT$cnI"] },
          shadow: false,
          topLevel: false,
        },
        c: {
          opcode: "control_if",
          next: "+",
          parent: "*",
          inputs: { CONDITION: [2, ","], SUBSTACK: [2, "bB"] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        ",": {
          opcode: "sensing_keypressed",
          next: null,
          parent: "c",
          inputs: { KEY_OPTION: [1, "bC"] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        bC: {
          opcode: "sensing_keyoptions",
          next: null,
          parent: ",",
          inputs: {},
          fields: { KEY_OPTION: ["up arrow", null] },
          shadow: true,
          topLevel: false,
        },
        bB: {
          opcode: "data_setvariableto",
          next: null,
          parent: "c",
          inputs: { VALUE: [1, [10, "12"]] },
          fields: { VARIABLE: ["speed y", "pT.e}n4RtL+`ZAiT$cnI"] },
          shadow: false,
          topLevel: false,
        },
        "+": {
          opcode: "procedures_call",
          next: "w",
          parent: "c",
          inputs: {},
          fields: {},
          shadow: false,
          topLevel: false,
          mutation: {
            tagName: "mutation",
            children: [],
            proccode: "move y",
            argumentids: "[]",
            warp: "true",
          },
        },
        w: {
          opcode: "looks_switchcostumeto",
          next: "d",
          parent: "+",
          inputs: { COSTUME: [1, "bD"] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        bD: {
          opcode: "looks_costume",
          next: null,
          parent: "w",
          inputs: {},
          fields: { COSTUME: ["move", null] },
          shadow: true,
          topLevel: false,
        },
        d: {
          opcode: "motion_gotoxy",
          next: "-",
          parent: "w",
          inputs: { X: [3, "bE", [4, ""]], Y: [3, "bF", [4, ""]] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        bE: {
          opcode: "operator_subtract",
          next: null,
          parent: "d",
          inputs: {
            NUM1: [3, [12, "player x", "Omb^c,YW;.!Uj1A7~oJ1"], [4, ""]],
            NUM2: [3, [12, "camera x", "+qm~UdN|JU.$.!V$*+Ka"], [4, ""]],
          },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        bF: {
          opcode: "operator_subtract",
          next: null,
          parent: "d",
          inputs: {
            NUM1: [3, [12, "player y", "e[7yT@wnA!3^S:!PNY~Q"], [4, ""]],
            NUM2: [3, [12, "camera y", ";sLdt+zV]./UgHiZH2)+"], [4, ""]],
          },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        "-": {
          opcode: "looks_switchcostumeto",
          next: null,
          parent: "d",
          inputs: { COSTUME: [1, "bG"] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        bG: {
          opcode: "looks_costume",
          next: null,
          parent: "-",
          inputs: {},
          fields: { COSTUME: ["player", null] },
          shadow: true,
          topLevel: false,
        },
        ".": {
          opcode: "procedures_definition",
          next: "e",
          parent: null,
          inputs: { custom_block: [1, "bH"] },
          fields: {},
          shadow: false,
          topLevel: true,
          x: 48,
          y: 2952,
        },
        bH: {
          opcode: "procedures_prototype",
          next: null,
          parent: ".",
          inputs: {},
          fields: {},
          shadow: true,
          topLevel: false,
          mutation: {
            tagName: "mutation",
            children: [],
            proccode: "collision y",
            argumentids: "[]",
            argumentnames: "[]",
            argumentdefaults: "[]",
            warp: "true",
          },
        },
        e: {
          opcode: "control_if",
          next: "f",
          parent: ".",
          inputs: { CONDITION: [2, "/"], SUBSTACK: [2, "x"] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        "/": {
          opcode: "operator_equals",
          next: null,
          parent: "e",
          inputs: {
            OPERAND1: [3, "y", [10, ""]],
            OPERAND2: [1, [10, "1"]],
          },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        y: {
          opcode: "operator_letter_of",
          next: null,
          parent: "/",
          inputs: {
            STRING: [3, ":", [10, ""]],
            LETTER: [3, ";", [6, ""]],
          },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        ":": {
          opcode: "data_itemoflist",
          next: null,
          parent: "y",
          inputs: { INDEX: [3, "=", [7, ""]] },
          fields: { LIST: ["world data", "/]:RR9WxA|~;a{XK,{rv"] },
          shadow: false,
          topLevel: false,
        },
        "=": {
          opcode: "operator_add",
          next: null,
          parent: ":",
          inputs: { NUM1: [3, "?", [4, ""]], NUM2: [1, [4, "9"]] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        "?": {
          opcode: "operator_round",
          next: null,
          parent: "=",
          inputs: { NUM: [3, "bI", [4, ""]] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        bI: {
          opcode: "operator_divide",
          next: null,
          parent: "?",
          inputs: {
            NUM1: [3, [12, "player y", "e[7yT@wnA!3^S:!PNY~Q"], [4, ""]],
            NUM2: [1, [4, "20"]],
          },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        ";": {
          opcode: "operator_add",
          next: null,
          parent: "y",
          inputs: { NUM1: [3, "@", [4, ""]], NUM2: [1, [4, "12"]] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        "@": {
          opcode: "operator_round",
          next: null,
          parent: ";",
          inputs: { NUM: [3, "bJ", [4, ""]] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        bJ: {
          opcode: "operator_divide",
          next: null,
          parent: "@",
          inputs: {
            NUM1: [3, [12, "player x", "Omb^c,YW;.!Uj1A7~oJ1"], [4, ""]],
            NUM2: [1, [4, "20"]],
          },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        x: {
          opcode: "data_setvariableto",
          next: "bK",
          parent: "e",
          inputs: { VALUE: [3, "[", [10, ""]] },
          fields: { VARIABLE: ["player y", "e[7yT@wnA!3^S:!PNY~Q"] },
          shadow: false,
          topLevel: false,
        },
        "[": {
          opcode: "operator_add",
          next: null,
          parent: "x",
          inputs: { NUM1: [3, "]", [4, ""]], NUM2: [1, [4, "10.1"]] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        "]": {
          opcode: "operator_multiply",
          next: null,
          parent: "[",
          inputs: { NUM1: [3, "^", [4, ""]], NUM2: [1, [4, "20"]] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        "^": {
          opcode: "operator_round",
          next: null,
          parent: "]",
          inputs: { NUM: [3, "_", [4, ""]] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        _: {
          opcode: "operator_divide",
          next: null,
          parent: "^",
          inputs: { NUM1: [3, "bL", [4, ""]], NUM2: [1, [4, "20"]] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        bL: {
          opcode: "operator_subtract",
          next: null,
          parent: "_",
          inputs: {
            NUM1: [3, [12, "player y", "e[7yT@wnA!3^S:!PNY~Q"], [4, ""]],
            NUM2: [1, [4, "10"]],
          },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        bK: {
          opcode: "data_setvariableto",
          next: null,
          parent: "x",
          inputs: { VALUE: [1, [10, "0"]] },
          fields: { VARIABLE: ["speed y", "pT.e}n4RtL+`ZAiT$cnI"] },
          shadow: false,
          topLevel: false,
        },
        f: {
          opcode: "control_if",
          next: "g",
          parent: "e",
          inputs: { CONDITION: [2, "`"], SUBSTACK: [2, "z"] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        "`": {
          opcode: "operator_equals",
          next: null,
          parent: "f",
          inputs: {
            OPERAND1: [3, "A", [10, ""]],
            OPERAND2: [1, [10, "1"]],
          },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        A: {
          opcode: "operator_letter_of",
          next: null,
          parent: "`",
          inputs: {
            STRING: [3, "{", [10, ""]],
            LETTER: [3, "|", [6, ""]],
          },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        "{": {
          opcode: "data_itemoflist",
          next: null,
          parent: "A",
          inputs: { INDEX: [3, "}", [7, ""]] },
          fields: { LIST: ["world data", "/]:RR9WxA|~;a{XK,{rv"] },
          shadow: false,
          topLevel: false,
        },
        "}": {
          opcode: "operator_add",
          next: null,
          parent: "{",
          inputs: { NUM1: [3, "~", [4, ""]], NUM2: [1, [4, "10"]] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        "~": {
          opcode: "operator_round",
          next: null,
          parent: "}",
          inputs: { NUM: [3, "bM", [4, ""]] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        bM: {
          opcode: "operator_divide",
          next: null,
          parent: "~",
          inputs: {
            NUM1: [3, [12, "player y", "e[7yT@wnA!3^S:!PNY~Q"], [4, ""]],
            NUM2: [1, [4, "20"]],
          },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        "|": {
          opcode: "operator_add",
          next: null,
          parent: "A",
          inputs: { NUM1: [3, "aa", [4, ""]], NUM2: [1, [4, "12"]] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        aa: {
          opcode: "operator_round",
          next: null,
          parent: "|",
          inputs: { NUM: [3, "bN", [4, ""]] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        bN: {
          opcode: "operator_divide",
          next: null,
          parent: "aa",
          inputs: {
            NUM1: [3, [12, "player x", "Omb^c,YW;.!Uj1A7~oJ1"], [4, ""]],
            NUM2: [1, [4, "20"]],
          },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        z: {
          opcode: "data_setvariableto",
          next: "bO",
          parent: "f",
          inputs: { VALUE: [3, "ab", [10, ""]] },
          fields: { VARIABLE: ["player y", "e[7yT@wnA!3^S:!PNY~Q"] },
          shadow: false,
          topLevel: false,
        },
        ab: {
          opcode: "operator_add",
          next: null,
          parent: "z",
          inputs: { NUM1: [3, "ac", [4, ""]], NUM2: [1, [4, "9.9"]] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        ac: {
          opcode: "operator_multiply",
          next: null,
          parent: "ab",
          inputs: { NUM1: [3, "ad", [4, ""]], NUM2: [1, [4, "20"]] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        ad: {
          opcode: "operator_round",
          next: null,
          parent: "ac",
          inputs: { NUM: [3, "ae", [4, ""]] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        ae: {
          opcode: "operator_divide",
          next: null,
          parent: "ad",
          inputs: { NUM1: [3, "bP", [4, ""]], NUM2: [1, [4, "20"]] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        bP: {
          opcode: "operator_subtract",
          next: null,
          parent: "ae",
          inputs: {
            NUM1: [3, [12, "player y", "e[7yT@wnA!3^S:!PNY~Q"], [4, ""]],
            NUM2: [1, [4, "10"]],
          },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        bO: {
          opcode: "data_setvariableto",
          next: null,
          parent: "z",
          inputs: { VALUE: [1, [10, "0"]] },
          fields: { VARIABLE: ["speed y", "pT.e}n4RtL+`ZAiT$cnI"] },
          shadow: false,
          topLevel: false,
        },
        g: {
          opcode: "control_if",
          next: "B",
          parent: "f",
          inputs: { CONDITION: [2, "af"], SUBSTACK: [2, "C"] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        af: {
          opcode: "operator_equals",
          next: null,
          parent: "g",
          inputs: {
            OPERAND1: [3, "D", [10, ""]],
            OPERAND2: [1, [10, "1"]],
          },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        D: {
          opcode: "operator_letter_of",
          next: null,
          parent: "af",
          inputs: {
            STRING: [3, "ag", [10, ""]],
            LETTER: [3, "ah", [6, ""]],
          },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        ag: {
          opcode: "data_itemoflist",
          next: null,
          parent: "D",
          inputs: { INDEX: [3, "ai", [7, ""]] },
          fields: { LIST: ["world data", "/]:RR9WxA|~;a{XK,{rv"] },
          shadow: false,
          topLevel: false,
        },
        ai: {
          opcode: "operator_add",
          next: null,
          parent: "ag",
          inputs: { NUM1: [3, "aj", [4, ""]], NUM2: [1, [4, "9"]] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        aj: {
          opcode: "operator_round",
          next: null,
          parent: "ai",
          inputs: { NUM: [3, "bQ", [4, ""]] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        bQ: {
          opcode: "operator_divide",
          next: null,
          parent: "aj",
          inputs: {
            NUM1: [3, [12, "player y", "e[7yT@wnA!3^S:!PNY~Q"], [4, ""]],
            NUM2: [1, [4, "20"]],
          },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        ah: {
          opcode: "operator_add",
          next: null,
          parent: "D",
          inputs: { NUM1: [3, "ak", [4, ""]], NUM2: [1, [4, "13"]] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        ak: {
          opcode: "operator_round",
          next: null,
          parent: "ah",
          inputs: { NUM: [3, "bR", [4, ""]] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        bR: {
          opcode: "operator_divide",
          next: null,
          parent: "ak",
          inputs: {
            NUM1: [3, [12, "player x", "Omb^c,YW;.!Uj1A7~oJ1"], [4, ""]],
            NUM2: [1, [4, "20"]],
          },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        C: {
          opcode: "data_setvariableto",
          next: "bS",
          parent: "g",
          inputs: { VALUE: [3, "al", [10, ""]] },
          fields: { VARIABLE: ["player y", "e[7yT@wnA!3^S:!PNY~Q"] },
          shadow: false,
          topLevel: false,
        },
        al: {
          opcode: "operator_add",
          next: null,
          parent: "C",
          inputs: { NUM1: [3, "am", [4, ""]], NUM2: [1, [4, "10.1"]] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        am: {
          opcode: "operator_multiply",
          next: null,
          parent: "al",
          inputs: { NUM1: [3, "an", [4, ""]], NUM2: [1, [4, "20"]] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        an: {
          opcode: "operator_round",
          next: null,
          parent: "am",
          inputs: { NUM: [3, "ao", [4, ""]] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        ao: {
          opcode: "operator_divide",
          next: null,
          parent: "an",
          inputs: { NUM1: [3, "bT", [4, ""]], NUM2: [1, [4, "20"]] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        bT: {
          opcode: "operator_subtract",
          next: null,
          parent: "ao",
          inputs: {
            NUM1: [3, [12, "player y", "e[7yT@wnA!3^S:!PNY~Q"], [4, ""]],
            NUM2: [1, [4, "10"]],
          },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        bS: {
          opcode: "data_setvariableto",
          next: null,
          parent: "C",
          inputs: { VALUE: [1, [10, "0"]] },
          fields: { VARIABLE: ["speed y", "pT.e}n4RtL+`ZAiT$cnI"] },
          shadow: false,
          topLevel: false,
        },
        B: {
          opcode: "control_if",
          next: null,
          parent: "g",
          inputs: { CONDITION: [2, "ap"], SUBSTACK: [2, "E"] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        ap: {
          opcode: "operator_equals",
          next: null,
          parent: "B",
          inputs: {
            OPERAND1: [3, "F", [10, ""]],
            OPERAND2: [1, [10, "1"]],
          },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        F: {
          opcode: "operator_letter_of",
          next: null,
          parent: "ap",
          inputs: {
            STRING: [3, "aq", [10, ""]],
            LETTER: [3, "ar", [6, ""]],
          },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        aq: {
          opcode: "data_itemoflist",
          next: null,
          parent: "F",
          inputs: { INDEX: [3, "as", [7, ""]] },
          fields: { LIST: ["world data", "/]:RR9WxA|~;a{XK,{rv"] },
          shadow: false,
          topLevel: false,
        },
        as: {
          opcode: "operator_add",
          next: null,
          parent: "aq",
          inputs: { NUM1: [3, "at", [4, ""]], NUM2: [1, [4, "10"]] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        at: {
          opcode: "operator_round",
          next: null,
          parent: "as",
          inputs: { NUM: [3, "bU", [4, ""]] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        bU: {
          opcode: "operator_divide",
          next: null,
          parent: "at",
          inputs: {
            NUM1: [3, [12, "player y", "e[7yT@wnA!3^S:!PNY~Q"], [4, ""]],
            NUM2: [1, [4, "20"]],
          },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        ar: {
          opcode: "operator_add",
          next: null,
          parent: "F",
          inputs: { NUM1: [3, "au", [4, ""]], NUM2: [1, [4, "13"]] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        au: {
          opcode: "operator_round",
          next: null,
          parent: "ar",
          inputs: { NUM: [3, "bV", [4, ""]] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        bV: {
          opcode: "operator_divide",
          next: null,
          parent: "au",
          inputs: {
            NUM1: [3, [12, "player x", "Omb^c,YW;.!Uj1A7~oJ1"], [4, ""]],
            NUM2: [1, [4, "20"]],
          },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        E: {
          opcode: "data_setvariableto",
          next: "bW",
          parent: "B",
          inputs: { VALUE: [3, "av", [10, ""]] },
          fields: { VARIABLE: ["player y", "e[7yT@wnA!3^S:!PNY~Q"] },
          shadow: false,
          topLevel: false,
        },
        av: {
          opcode: "operator_add",
          next: null,
          parent: "E",
          inputs: { NUM1: [3, "aw", [4, ""]], NUM2: [1, [4, "9.9"]] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        aw: {
          opcode: "operator_multiply",
          next: null,
          parent: "av",
          inputs: { NUM1: [3, "ax", [4, ""]], NUM2: [1, [4, "20"]] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        ax: {
          opcode: "operator_round",
          next: null,
          parent: "aw",
          inputs: { NUM: [3, "ay", [4, ""]] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        ay: {
          opcode: "operator_divide",
          next: null,
          parent: "ax",
          inputs: { NUM1: [3, "bX", [4, ""]], NUM2: [1, [4, "20"]] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        bX: {
          opcode: "operator_subtract",
          next: null,
          parent: "ay",
          inputs: {
            NUM1: [3, [12, "player y", "e[7yT@wnA!3^S:!PNY~Q"], [4, ""]],
            NUM2: [1, [4, "10"]],
          },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        bW: {
          opcode: "data_setvariableto",
          next: null,
          parent: "E",
          inputs: { VALUE: [1, [10, "0"]] },
          fields: { VARIABLE: ["speed y", "pT.e}n4RtL+`ZAiT$cnI"] },
          shadow: false,
          topLevel: false,
        },
        az: {
          opcode: "procedures_definition",
          next: "h",
          parent: null,
          inputs: { custom_block: [1, "bY"] },
          fields: {},
          shadow: false,
          topLevel: true,
          x: 48,
          y: 1240,
        },
        bY: {
          opcode: "procedures_prototype",
          next: null,
          parent: "az",
          inputs: {},
          fields: {},
          shadow: true,
          topLevel: false,
          mutation: {
            tagName: "mutation",
            children: [],
            proccode: "move x",
            argumentids: "[]",
            argumentnames: "[]",
            argumentdefaults: "[]",
            warp: "true",
          },
        },
        h: {
          opcode: "control_if_else",
          next: null,
          parent: "az",
          inputs: {
            CONDITION: [2, "bZ"],
            SUBSTACK: [2, "i"],
            SUBSTACK2: [2, "j"],
          },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        bZ: {
          opcode: "operator_gt",
          next: null,
          parent: "h",
          inputs: {
            OPERAND1: [3, [12, "speed x", "$/yw+8k;*81pDO7cl%%P"], [10, ""]],
            OPERAND2: [1, [10, "0"]],
          },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        i: {
          opcode: "control_repeat",
          next: "G",
          parent: "h",
          inputs: { TIMES: [3, "aA", [6, ""]], SUBSTACK: [2, "aB"] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        aA: {
          opcode: "operator_mathop",
          next: null,
          parent: "i",
          inputs: { NUM: [3, "b!", [4, ""]] },
          fields: { OPERATOR: ["floor", null] },
          shadow: false,
          topLevel: false,
        },
        "b!": {
          opcode: "operator_divide",
          next: null,
          parent: "aA",
          inputs: {
            NUM1: [3, [12, "speed x", "$/yw+8k;*81pDO7cl%%P"], [4, ""]],
            NUM2: [1, [4, "10"]],
          },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        aB: {
          opcode: "data_changevariableby",
          next: "b#",
          parent: "i",
          inputs: { VALUE: [1, [4, "10"]] },
          fields: { VARIABLE: ["player x", "Omb^c,YW;.!Uj1A7~oJ1"] },
          shadow: false,
          topLevel: false,
        },
        "b#": {
          opcode: "procedures_call",
          next: null,
          parent: "aB",
          inputs: {},
          fields: {},
          shadow: false,
          topLevel: false,
          mutation: {
            tagName: "mutation",
            children: [],
            proccode: "collision x",
            argumentids: "[]",
            warp: "false",
          },
        },
        G: {
          opcode: "data_changevariableby",
          next: "b%",
          parent: "i",
          inputs: { VALUE: [3, "b(", [4, ""]] },
          fields: { VARIABLE: ["player x", "Omb^c,YW;.!Uj1A7~oJ1"] },
          shadow: false,
          topLevel: false,
        },
        "b(": {
          opcode: "operator_mod",
          next: null,
          parent: "G",
          inputs: {
            NUM1: [3, [12, "speed x", "$/yw+8k;*81pDO7cl%%P"], [4, ""]],
            NUM2: [1, [4, "10"]],
          },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        "b%": {
          opcode: "procedures_call",
          next: null,
          parent: "G",
          inputs: {},
          fields: {},
          shadow: false,
          topLevel: false,
          mutation: {
            tagName: "mutation",
            children: [],
            proccode: "collision x",
            argumentids: "[]",
            warp: "false",
          },
        },
        j: {
          opcode: "control_repeat",
          next: "H",
          parent: "h",
          inputs: { TIMES: [3, "aC", [6, ""]], SUBSTACK: [2, "aD"] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        aC: {
          opcode: "operator_mathop",
          next: null,
          parent: "j",
          inputs: { NUM: [3, "b)", [4, ""]] },
          fields: { OPERATOR: ["floor", null] },
          shadow: false,
          topLevel: false,
        },
        "b)": {
          opcode: "operator_divide",
          next: null,
          parent: "aC",
          inputs: {
            NUM1: [3, [12, "speed x", "$/yw+8k;*81pDO7cl%%P"], [4, ""]],
            NUM2: [1, [4, "-10"]],
          },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        aD: {
          opcode: "data_changevariableby",
          next: "b*",
          parent: "j",
          inputs: { VALUE: [1, [4, "-10"]] },
          fields: { VARIABLE: ["player x", "Omb^c,YW;.!Uj1A7~oJ1"] },
          shadow: false,
          topLevel: false,
        },
        "b*": {
          opcode: "procedures_call",
          next: null,
          parent: "aD",
          inputs: {},
          fields: {},
          shadow: false,
          topLevel: false,
          mutation: {
            tagName: "mutation",
            children: [],
            proccode: "collision x",
            argumentids: "[]",
            warp: "false",
          },
        },
        H: {
          opcode: "data_changevariableby",
          next: "b+",
          parent: "j",
          inputs: { VALUE: [3, "b,", [4, ""]] },
          fields: { VARIABLE: ["player x", "Omb^c,YW;.!Uj1A7~oJ1"] },
          shadow: false,
          topLevel: false,
        },
        "b,": {
          opcode: "operator_mod",
          next: null,
          parent: "H",
          inputs: {
            NUM1: [3, [12, "speed x", "$/yw+8k;*81pDO7cl%%P"], [4, ""]],
            NUM2: [1, [4, "-10"]],
          },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        "b+": {
          opcode: "procedures_call",
          next: null,
          parent: "H",
          inputs: {},
          fields: {},
          shadow: false,
          topLevel: false,
          mutation: {
            tagName: "mutation",
            children: [],
            proccode: "collision x",
            argumentids: "[]",
            warp: "false",
          },
        },
        aE: {
          opcode: "procedures_definition",
          next: "k",
          parent: null,
          inputs: { custom_block: [1, "b-"] },
          fields: {},
          shadow: false,
          topLevel: true,
          x: 48,
          y: 2096,
        },
        "b-": {
          opcode: "procedures_prototype",
          next: null,
          parent: "aE",
          inputs: {},
          fields: {},
          shadow: true,
          topLevel: false,
          mutation: {
            tagName: "mutation",
            children: [],
            proccode: "move y",
            argumentids: "[]",
            argumentnames: "[]",
            argumentdefaults: "[]",
            warp: "true",
          },
        },
        k: {
          opcode: "control_if_else",
          next: null,
          parent: "aE",
          inputs: {
            CONDITION: [2, "b."],
            SUBSTACK: [2, "l"],
            SUBSTACK2: [2, "m"],
          },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        "b.": {
          opcode: "operator_gt",
          next: null,
          parent: "k",
          inputs: {
            OPERAND1: [3, [12, "speed y", "pT.e}n4RtL+`ZAiT$cnI"], [10, ""]],
            OPERAND2: [1, [10, "0"]],
          },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        l: {
          opcode: "control_repeat",
          next: "I",
          parent: "k",
          inputs: { TIMES: [3, "aF", [6, ""]], SUBSTACK: [2, "aG"] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        aF: {
          opcode: "operator_mathop",
          next: null,
          parent: "l",
          inputs: { NUM: [3, "b/", [4, ""]] },
          fields: { OPERATOR: ["floor", null] },
          shadow: false,
          topLevel: false,
        },
        "b/": {
          opcode: "operator_divide",
          next: null,
          parent: "aF",
          inputs: {
            NUM1: [3, [12, "speed y", "pT.e}n4RtL+`ZAiT$cnI"], [4, ""]],
            NUM2: [1, [4, "10"]],
          },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        aG: {
          opcode: "data_changevariableby",
          next: "b:",
          parent: "l",
          inputs: { VALUE: [1, [4, "10"]] },
          fields: { VARIABLE: ["player y", "e[7yT@wnA!3^S:!PNY~Q"] },
          shadow: false,
          topLevel: false,
        },
        "b:": {
          opcode: "procedures_call",
          next: null,
          parent: "aG",
          inputs: {},
          fields: {},
          shadow: false,
          topLevel: false,
          mutation: {
            tagName: "mutation",
            children: [],
            proccode: "collision y",
            argumentids: "[]",
            warp: "true",
          },
        },
        I: {
          opcode: "data_changevariableby",
          next: "b;",
          parent: "l",
          inputs: { VALUE: [3, "b=", [4, ""]] },
          fields: { VARIABLE: ["player y", "e[7yT@wnA!3^S:!PNY~Q"] },
          shadow: false,
          topLevel: false,
        },
        "b=": {
          opcode: "operator_mod",
          next: null,
          parent: "I",
          inputs: {
            NUM1: [3, [12, "speed y", "pT.e}n4RtL+`ZAiT$cnI"], [4, ""]],
            NUM2: [1, [4, "10"]],
          },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        "b;": {
          opcode: "procedures_call",
          next: null,
          parent: "I",
          inputs: {},
          fields: {},
          shadow: false,
          topLevel: false,
          mutation: {
            tagName: "mutation",
            children: [],
            proccode: "collision y",
            argumentids: "[]",
            warp: "true",
          },
        },
        m: {
          opcode: "control_repeat",
          next: "J",
          parent: "k",
          inputs: { TIMES: [3, "aH", [6, ""]], SUBSTACK: [2, "aI"] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        aH: {
          opcode: "operator_mathop",
          next: null,
          parent: "m",
          inputs: { NUM: [3, "b?", [4, ""]] },
          fields: { OPERATOR: ["floor", null] },
          shadow: false,
          topLevel: false,
        },
        "b?": {
          opcode: "operator_divide",
          next: null,
          parent: "aH",
          inputs: {
            NUM1: [3, [12, "speed y", "pT.e}n4RtL+`ZAiT$cnI"], [4, ""]],
            NUM2: [1, [4, "-10"]],
          },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        aI: {
          opcode: "data_changevariableby",
          next: "b@",
          parent: "m",
          inputs: { VALUE: [1, [4, "-10"]] },
          fields: { VARIABLE: ["player y", "e[7yT@wnA!3^S:!PNY~Q"] },
          shadow: false,
          topLevel: false,
        },
        "b@": {
          opcode: "procedures_call",
          next: null,
          parent: "aI",
          inputs: {},
          fields: {},
          shadow: false,
          topLevel: false,
          mutation: {
            tagName: "mutation",
            children: [],
            proccode: "collision y",
            argumentids: "[]",
            warp: "true",
          },
        },
        J: {
          opcode: "data_changevariableby",
          next: "b[",
          parent: "m",
          inputs: { VALUE: [3, "b]", [4, ""]] },
          fields: { VARIABLE: ["player y", "e[7yT@wnA!3^S:!PNY~Q"] },
          shadow: false,
          topLevel: false,
        },
        "b]": {
          opcode: "operator_mod",
          next: null,
          parent: "J",
          inputs: {
            NUM1: [3, [12, "speed y", "pT.e}n4RtL+`ZAiT$cnI"], [4, ""]],
            NUM2: [1, [4, "-10"]],
          },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        "b[": {
          opcode: "procedures_call",
          next: null,
          parent: "J",
          inputs: {},
          fields: {},
          shadow: false,
          topLevel: false,
          mutation: {
            tagName: "mutation",
            children: [],
            proccode: "collision y",
            argumentids: "[]",
            warp: "true",
          },
        },
        aJ: {
          opcode: "procedures_definition",
          next: "n",
          parent: null,
          inputs: { custom_block: [1, "b^"] },
          fields: {},
          shadow: false,
          topLevel: true,
          x: 1368,
          y: 64,
        },
        "b^": {
          opcode: "procedures_prototype",
          next: null,
          parent: "aJ",
          inputs: {},
          fields: {},
          shadow: true,
          topLevel: false,
          mutation: {
            tagName: "mutation",
            children: [],
            proccode: "collision x",
            argumentids: "[]",
            argumentnames: "[]",
            argumentdefaults: "[]",
            warp: "false",
          },
        },
        n: {
          opcode: "control_if",
          next: "o",
          parent: "aJ",
          inputs: { CONDITION: [2, "aK"], SUBSTACK: [2, "K"] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        aK: {
          opcode: "operator_equals",
          next: null,
          parent: "n",
          inputs: {
            OPERAND1: [3, "L", [10, ""]],
            OPERAND2: [1, [10, "1"]],
          },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        L: {
          opcode: "operator_letter_of",
          next: null,
          parent: "aK",
          inputs: {
            STRING: [3, "aL", [10, ""]],
            LETTER: [3, "aM", [6, ""]],
          },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        aL: {
          opcode: "data_itemoflist",
          next: null,
          parent: "L",
          inputs: { INDEX: [3, "aN", [7, ""]] },
          fields: { LIST: ["world data", "/]:RR9WxA|~;a{XK,{rv"] },
          shadow: false,
          topLevel: false,
        },
        aN: {
          opcode: "operator_add",
          next: null,
          parent: "aL",
          inputs: { NUM1: [3, "aO", [4, ""]], NUM2: [1, [4, "9"]] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        aO: {
          opcode: "operator_round",
          next: null,
          parent: "aN",
          inputs: { NUM: [3, "b_", [4, ""]] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        b_: {
          opcode: "operator_divide",
          next: null,
          parent: "aO",
          inputs: {
            NUM1: [3, [12, "player y", "e[7yT@wnA!3^S:!PNY~Q"], [4, ""]],
            NUM2: [1, [4, "20"]],
          },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        aM: {
          opcode: "operator_add",
          next: null,
          parent: "L",
          inputs: { NUM1: [3, "aP", [4, ""]], NUM2: [1, [4, "12"]] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        aP: {
          opcode: "operator_round",
          next: null,
          parent: "aM",
          inputs: { NUM: [3, "b`", [4, ""]] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        "b`": {
          opcode: "operator_divide",
          next: null,
          parent: "aP",
          inputs: {
            NUM1: [3, [12, "player x", "Omb^c,YW;.!Uj1A7~oJ1"], [4, ""]],
            NUM2: [1, [4, "20"]],
          },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        K: {
          opcode: "data_setvariableto",
          next: "b{",
          parent: "n",
          inputs: { VALUE: [3, "aQ", [10, ""]] },
          fields: { VARIABLE: ["player x", "Omb^c,YW;.!Uj1A7~oJ1"] },
          shadow: false,
          topLevel: false,
        },
        aQ: {
          opcode: "operator_add",
          next: null,
          parent: "K",
          inputs: { NUM1: [3, "aR", [4, ""]], NUM2: [1, [4, "10.1"]] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        aR: {
          opcode: "operator_multiply",
          next: null,
          parent: "aQ",
          inputs: { NUM1: [3, "aS", [4, ""]], NUM2: [1, [4, "20"]] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        aS: {
          opcode: "operator_round",
          next: null,
          parent: "aR",
          inputs: { NUM: [3, "aT", [4, ""]] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        aT: {
          opcode: "operator_divide",
          next: null,
          parent: "aS",
          inputs: { NUM1: [3, "b|", [4, ""]], NUM2: [1, [4, "20"]] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        "b|": {
          opcode: "operator_subtract",
          next: null,
          parent: "aT",
          inputs: {
            NUM1: [3, [12, "player x", "Omb^c,YW;.!Uj1A7~oJ1"], [4, ""]],
            NUM2: [1, [4, "10"]],
          },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        "b{": {
          opcode: "data_setvariableto",
          next: null,
          parent: "K",
          inputs: { VALUE: [1, [10, "0"]] },
          fields: { VARIABLE: ["speed x", "$/yw+8k;*81pDO7cl%%P"] },
          shadow: false,
          topLevel: false,
        },
        o: {
          opcode: "control_if",
          next: "p",
          parent: "n",
          inputs: { CONDITION: [2, "aU"], SUBSTACK: [2, "M"] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        aU: {
          opcode: "operator_equals",
          next: null,
          parent: "o",
          inputs: {
            OPERAND1: [3, "N", [10, ""]],
            OPERAND2: [1, [10, "1"]],
          },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        N: {
          opcode: "operator_letter_of",
          next: null,
          parent: "aU",
          inputs: {
            STRING: [3, "aV", [10, ""]],
            LETTER: [3, "aW", [6, ""]],
          },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        aV: {
          opcode: "data_itemoflist",
          next: null,
          parent: "N",
          inputs: { INDEX: [3, "aX", [7, ""]] },
          fields: { LIST: ["world data", "/]:RR9WxA|~;a{XK,{rv"] },
          shadow: false,
          topLevel: false,
        },
        aX: {
          opcode: "operator_add",
          next: null,
          parent: "aV",
          inputs: { NUM1: [3, "aY", [4, ""]], NUM2: [1, [4, "10"]] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        aY: {
          opcode: "operator_round",
          next: null,
          parent: "aX",
          inputs: { NUM: [3, "b}", [4, ""]] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        "b}": {
          opcode: "operator_divide",
          next: null,
          parent: "aY",
          inputs: {
            NUM1: [3, [12, "player y", "e[7yT@wnA!3^S:!PNY~Q"], [4, ""]],
            NUM2: [1, [4, "20"]],
          },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        aW: {
          opcode: "operator_add",
          next: null,
          parent: "N",
          inputs: { NUM1: [3, "aZ", [4, ""]], NUM2: [1, [4, "12"]] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        aZ: {
          opcode: "operator_round",
          next: null,
          parent: "aW",
          inputs: { NUM: [3, "b~", [4, ""]] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        "b~": {
          opcode: "operator_divide",
          next: null,
          parent: "aZ",
          inputs: {
            NUM1: [3, [12, "player x", "Omb^c,YW;.!Uj1A7~oJ1"], [4, ""]],
            NUM2: [1, [4, "20"]],
          },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        M: {
          opcode: "data_setvariableto",
          next: "ca",
          parent: "o",
          inputs: { VALUE: [3, "a!", [10, ""]] },
          fields: { VARIABLE: ["player x", "Omb^c,YW;.!Uj1A7~oJ1"] },
          shadow: false,
          topLevel: false,
        },
        "a!": {
          opcode: "operator_add",
          next: null,
          parent: "M",
          inputs: { NUM1: [3, "a#", [4, ""]], NUM2: [1, [4, "10.1"]] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        "a#": {
          opcode: "operator_multiply",
          next: null,
          parent: "a!",
          inputs: { NUM1: [3, "a%", [4, ""]], NUM2: [1, [4, "20"]] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        "a%": {
          opcode: "operator_round",
          next: null,
          parent: "a#",
          inputs: { NUM: [3, "a(", [4, ""]] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        "a(": {
          opcode: "operator_divide",
          next: null,
          parent: "a%",
          inputs: { NUM1: [3, "cb", [4, ""]], NUM2: [1, [4, "20"]] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        cb: {
          opcode: "operator_subtract",
          next: null,
          parent: "a(",
          inputs: {
            NUM1: [3, [12, "player x", "Omb^c,YW;.!Uj1A7~oJ1"], [4, ""]],
            NUM2: [1, [4, "10"]],
          },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        ca: {
          opcode: "data_setvariableto",
          next: null,
          parent: "M",
          inputs: { VALUE: [1, [10, "0"]] },
          fields: { VARIABLE: ["speed x", "$/yw+8k;*81pDO7cl%%P"] },
          shadow: false,
          topLevel: false,
        },
        p: {
          opcode: "control_if",
          next: "O",
          parent: "o",
          inputs: { CONDITION: [2, "a)"], SUBSTACK: [2, "P"] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        "a)": {
          opcode: "operator_equals",
          next: null,
          parent: "p",
          inputs: {
            OPERAND1: [3, "Q", [10, ""]],
            OPERAND2: [1, [10, "1"]],
          },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        Q: {
          opcode: "operator_letter_of",
          next: null,
          parent: "a)",
          inputs: {
            STRING: [3, "a*", [10, ""]],
            LETTER: [3, "a+", [6, ""]],
          },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        "a*": {
          opcode: "data_itemoflist",
          next: null,
          parent: "Q",
          inputs: { INDEX: [3, "a,", [7, ""]] },
          fields: { LIST: ["world data", "/]:RR9WxA|~;a{XK,{rv"] },
          shadow: false,
          topLevel: false,
        },
        "a,": {
          opcode: "operator_add",
          next: null,
          parent: "a*",
          inputs: { NUM1: [3, "a-", [4, ""]], NUM2: [1, [4, "9"]] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        "a-": {
          opcode: "operator_round",
          next: null,
          parent: "a,",
          inputs: { NUM: [3, "cc", [4, ""]] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        cc: {
          opcode: "operator_divide",
          next: null,
          parent: "a-",
          inputs: {
            NUM1: [3, [12, "player y", "e[7yT@wnA!3^S:!PNY~Q"], [4, ""]],
            NUM2: [1, [4, "20"]],
          },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        "a+": {
          opcode: "operator_add",
          next: null,
          parent: "Q",
          inputs: { NUM1: [3, "a.", [4, ""]], NUM2: [1, [4, "13"]] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        "a.": {
          opcode: "operator_round",
          next: null,
          parent: "a+",
          inputs: { NUM: [3, "cd", [4, ""]] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        cd: {
          opcode: "operator_divide",
          next: null,
          parent: "a.",
          inputs: {
            NUM1: [3, [12, "player x", "Omb^c,YW;.!Uj1A7~oJ1"], [4, ""]],
            NUM2: [1, [4, "20"]],
          },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        P: {
          opcode: "data_setvariableto",
          next: "ce",
          parent: "p",
          inputs: { VALUE: [3, "a/", [10, ""]] },
          fields: { VARIABLE: ["player x", "Omb^c,YW;.!Uj1A7~oJ1"] },
          shadow: false,
          topLevel: false,
        },
        "a/": {
          opcode: "operator_add",
          next: null,
          parent: "P",
          inputs: { NUM1: [3, "a:", [4, ""]], NUM2: [1, [4, "9.9"]] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        "a:": {
          opcode: "operator_multiply",
          next: null,
          parent: "a/",
          inputs: { NUM1: [3, "a;", [4, ""]], NUM2: [1, [4, "20"]] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        "a;": {
          opcode: "operator_round",
          next: null,
          parent: "a:",
          inputs: { NUM: [3, "a=", [4, ""]] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        "a=": {
          opcode: "operator_divide",
          next: null,
          parent: "a;",
          inputs: { NUM1: [3, "cf", [4, ""]], NUM2: [1, [4, "20"]] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        cf: {
          opcode: "operator_subtract",
          next: null,
          parent: "a=",
          inputs: {
            NUM1: [3, [12, "player x", "Omb^c,YW;.!Uj1A7~oJ1"], [4, ""]],
            NUM2: [1, [4, "10"]],
          },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        ce: {
          opcode: "data_setvariableto",
          next: null,
          parent: "P",
          inputs: { VALUE: [1, [10, "0"]] },
          fields: { VARIABLE: ["speed x", "$/yw+8k;*81pDO7cl%%P"] },
          shadow: false,
          topLevel: false,
        },
        O: {
          opcode: "control_if",
          next: null,
          parent: "p",
          inputs: { CONDITION: [2, "a?"], SUBSTACK: [2, "R"] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        "a?": {
          opcode: "operator_equals",
          next: null,
          parent: "O",
          inputs: {
            OPERAND1: [3, "S", [10, ""]],
            OPERAND2: [1, [10, "1"]],
          },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        S: {
          opcode: "operator_letter_of",
          next: null,
          parent: "a?",
          inputs: {
            STRING: [3, "a@", [10, ""]],
            LETTER: [3, "a[", [6, ""]],
          },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        "a@": {
          opcode: "data_itemoflist",
          next: null,
          parent: "S",
          inputs: { INDEX: [3, "a]", [7, ""]] },
          fields: { LIST: ["world data", "/]:RR9WxA|~;a{XK,{rv"] },
          shadow: false,
          topLevel: false,
        },
        "a]": {
          opcode: "operator_add",
          next: null,
          parent: "a@",
          inputs: { NUM1: [3, "a^", [4, ""]], NUM2: [1, [4, "10"]] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        "a^": {
          opcode: "operator_round",
          next: null,
          parent: "a]",
          inputs: { NUM: [3, "cg", [4, ""]] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        cg: {
          opcode: "operator_divide",
          next: null,
          parent: "a^",
          inputs: {
            NUM1: [3, [12, "player y", "e[7yT@wnA!3^S:!PNY~Q"], [4, ""]],
            NUM2: [1, [4, "20"]],
          },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        "a[": {
          opcode: "operator_add",
          next: null,
          parent: "S",
          inputs: { NUM1: [3, "a_", [4, ""]], NUM2: [1, [4, "13"]] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        a_: {
          opcode: "operator_round",
          next: null,
          parent: "a[",
          inputs: { NUM: [3, "ch", [4, ""]] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        ch: {
          opcode: "operator_divide",
          next: null,
          parent: "a_",
          inputs: {
            NUM1: [3, [12, "player x", "Omb^c,YW;.!Uj1A7~oJ1"], [4, ""]],
            NUM2: [1, [4, "20"]],
          },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        R: {
          opcode: "data_setvariableto",
          next: "ci",
          parent: "O",
          inputs: { VALUE: [3, "a`", [10, ""]] },
          fields: { VARIABLE: ["player x", "Omb^c,YW;.!Uj1A7~oJ1"] },
          shadow: false,
          topLevel: false,
        },
        "a`": {
          opcode: "operator_add",
          next: null,
          parent: "R",
          inputs: { NUM1: [3, "a{", [4, ""]], NUM2: [1, [4, "9.9"]] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        "a{": {
          opcode: "operator_multiply",
          next: null,
          parent: "a`",
          inputs: { NUM1: [3, "a|", [4, ""]], NUM2: [1, [4, "20"]] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        "a|": {
          opcode: "operator_round",
          next: null,
          parent: "a{",
          inputs: { NUM: [3, "a}", [4, ""]] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        "a}": {
          opcode: "operator_divide",
          next: null,
          parent: "a|",
          inputs: { NUM1: [3, "cj", [4, ""]], NUM2: [1, [4, "20"]] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        cj: {
          opcode: "operator_subtract",
          next: null,
          parent: "a}",
          inputs: {
            NUM1: [3, [12, "player x", "Omb^c,YW;.!Uj1A7~oJ1"], [4, ""]],
            NUM2: [1, [4, "10"]],
          },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        ci: {
          opcode: "data_setvariableto",
          next: null,
          parent: "R",
          inputs: { VALUE: [1, [10, "0"]] },
          fields: { VARIABLE: ["speed x", "$/yw+8k;*81pDO7cl%%P"] },
          shadow: false,
          topLevel: false,
        },
      },
      comments: {},
      currentCostume: 0,
      costumes: [
        {
          name: "player",
          bitmapResolution: 1,
          dataFormat: "svg",
          assetId: "521f4579817269a02344283d7a201fd5",
          md5ext: "521f4579817269a02344283d7a201fd5.svg",
          rotationCenterX: 10,
          rotationCenterY: 10,
        },
        {
          name: "move",
          bitmapResolution: 1,
          dataFormat: "svg",
          assetId: "8366d3f8863b6589493be6afe22408e2",
          md5ext: "8366d3f8863b6589493be6afe22408e2.svg",
          rotationCenterX: 270.5,
          rotationCenterY: 203,
        },
      ],
      sounds: [],
      volume: 100,
      layerOrder: 2,
      visible: true,
      x: -2.842170943040401e-14,
      y: -350.0066461399788,
      size: 100,
      direction: 90,
      draggable: false,
      rotationStyle: "all around",
    },
    {
      isStage: false,
      name: "world",
      variables: {
        "29zCYncZ6{;WJ.7N4k8B": ["clone x", 0],
        "(mJi~`u5kn]QxBOc,Bj9": ["clone y", 0],
      },
      lists: {},
      broadcasts: {},
      blocks: {
        ck: {
          opcode: "event_whenflagclicked",
          next: "a~",
          parent: null,
          inputs: {},
          fields: {},
          shadow: false,
          topLevel: true,
          x: 48,
          y: 64,
        },
        "a~": {
          opcode: "looks_hide",
          next: "cl",
          parent: "ck",
          inputs: {},
          fields: {},
          shadow: false,
          topLevel: false,
        },
        cl: {
          opcode: "procedures_call",
          next: null,
          parent: "a~",
          inputs: {},
          fields: {},
          shadow: false,
          topLevel: false,
          mutation: {
            tagName: "mutation",
            children: [],
            proccode: "clone create",
            argumentids: "[]",
            warp: "true",
          },
        },
        ba: {
          opcode: "procedures_definition",
          next: "bb",
          parent: null,
          inputs: { custom_block: [1, "cm"] },
          fields: {},
          shadow: false,
          topLevel: true,
          x: 48,
          y: 288,
        },
        cm: {
          opcode: "procedures_prototype",
          next: null,
          parent: "ba",
          inputs: {},
          fields: {},
          shadow: true,
          topLevel: false,
          mutation: {
            tagName: "mutation",
            children: [],
            proccode: "clone create",
            argumentids: "[]",
            argumentnames: "[]",
            argumentdefaults: "[]",
            warp: "true",
          },
        },
        bb: {
          opcode: "data_setvariableto",
          next: "bc",
          parent: "ba",
          inputs: { VALUE: [1, [10, "-360"]] },
          fields: { VARIABLE: ["clone y", "(mJi~`u5kn]QxBOc,Bj9"] },
          shadow: false,
          topLevel: false,
        },
        bc: {
          opcode: "control_repeat",
          next: null,
          parent: "bb",
          inputs: { TIMES: [1, [6, "2"]], SUBSTACK: [2, "bd"] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        bd: {
          opcode: "data_setvariableto",
          next: "be",
          parent: "bc",
          inputs: { VALUE: [1, [10, "-480"]] },
          fields: { VARIABLE: ["clone x", "29zCYncZ6{;WJ.7N4k8B"] },
          shadow: false,
          topLevel: false,
        },
        be: {
          opcode: "data_changevariableby",
          next: "bf",
          parent: "bd",
          inputs: { VALUE: [1, [4, "360"]] },
          fields: { VARIABLE: ["clone y", "(mJi~`u5kn]QxBOc,Bj9"] },
          shadow: false,
          topLevel: false,
        },
        bf: {
          opcode: "control_repeat",
          next: null,
          parent: "be",
          inputs: { TIMES: [1, [6, "2"]], SUBSTACK: [2, "bg"] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        bg: {
          opcode: "data_changevariableby",
          next: "bh",
          parent: "bf",
          inputs: { VALUE: [1, [4, "480"]] },
          fields: { VARIABLE: ["clone x", "29zCYncZ6{;WJ.7N4k8B"] },
          shadow: false,
          topLevel: false,
        },
        bh: {
          opcode: "control_create_clone_of",
          next: null,
          parent: "bg",
          inputs: { CLONE_OPTION: [1, "cn"] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        cn: {
          opcode: "control_create_clone_of_menu",
          next: null,
          parent: "bh",
          inputs: {},
          fields: { CLONE_OPTION: ["_myself_", null] },
          shadow: true,
          topLevel: false,
        },
        co: {
          opcode: "control_start_as_clone",
          next: "bi",
          parent: null,
          inputs: {},
          fields: {},
          shadow: false,
          topLevel: true,
          x: 48,
          y: 832,
        },
        bi: {
          opcode: "looks_show",
          next: "bj",
          parent: "co",
          inputs: {},
          fields: {},
          shadow: false,
          topLevel: false,
        },
        bj: {
          opcode: "control_forever",
          next: null,
          parent: "bi",
          inputs: { SUBSTACK: [2, "q"] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        q: {
          opcode: "control_if",
          next: "r",
          parent: "bj",
          inputs: { CONDITION: [2, "bk"], SUBSTACK: [2, "cp"] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        bk: {
          opcode: "operator_gt",
          next: null,
          parent: "q",
          inputs: {
            OPERAND1: [3, "cq", [10, ""]],
            OPERAND2: [1, [10, "480"]],
          },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        cq: {
          opcode: "operator_subtract",
          next: null,
          parent: "bk",
          inputs: {
            NUM1: [3, [12, "clone x", "29zCYncZ6{;WJ.7N4k8B"], [4, ""]],
            NUM2: [3, [12, "camera x", "+qm~UdN|JU.$.!V$*+Ka"], [4, ""]],
          },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        cp: {
          opcode: "data_changevariableby",
          next: null,
          parent: "q",
          inputs: { VALUE: [1, [4, "-960"]] },
          fields: { VARIABLE: ["clone x", "29zCYncZ6{;WJ.7N4k8B"] },
          shadow: false,
          topLevel: false,
        },
        r: {
          opcode: "control_if",
          next: "s",
          parent: "q",
          inputs: { CONDITION: [2, "bl"], SUBSTACK: [2, "cr"] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        bl: {
          opcode: "operator_lt",
          next: null,
          parent: "r",
          inputs: {
            OPERAND1: [3, "cs", [10, ""]],
            OPERAND2: [1, [10, "-480"]],
          },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        cs: {
          opcode: "operator_subtract",
          next: null,
          parent: "bl",
          inputs: {
            NUM1: [3, [12, "clone x", "29zCYncZ6{;WJ.7N4k8B"], [4, ""]],
            NUM2: [3, [12, "camera x", "+qm~UdN|JU.$.!V$*+Ka"], [4, ""]],
          },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        cr: {
          opcode: "data_changevariableby",
          next: null,
          parent: "r",
          inputs: { VALUE: [1, [4, "960"]] },
          fields: { VARIABLE: ["clone x", "29zCYncZ6{;WJ.7N4k8B"] },
          shadow: false,
          topLevel: false,
        },
        s: {
          opcode: "control_if",
          next: "t",
          parent: "r",
          inputs: { CONDITION: [2, "bm"], SUBSTACK: [2, "ct"] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        bm: {
          opcode: "operator_gt",
          next: null,
          parent: "s",
          inputs: {
            OPERAND1: [3, "cu", [10, ""]],
            OPERAND2: [1, [10, "360"]],
          },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        cu: {
          opcode: "operator_subtract",
          next: null,
          parent: "bm",
          inputs: {
            NUM1: [3, [12, "clone y", "(mJi~`u5kn]QxBOc,Bj9"], [4, ""]],
            NUM2: [3, [12, "camera y", ";sLdt+zV]./UgHiZH2)+"], [4, ""]],
          },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        ct: {
          opcode: "data_changevariableby",
          next: null,
          parent: "s",
          inputs: { VALUE: [1, [4, "-720"]] },
          fields: { VARIABLE: ["clone y", "(mJi~`u5kn]QxBOc,Bj9"] },
          shadow: false,
          topLevel: false,
        },
        t: {
          opcode: "control_if",
          next: "T",
          parent: "s",
          inputs: { CONDITION: [2, "bn"], SUBSTACK: [2, "cv"] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        bn: {
          opcode: "operator_lt",
          next: null,
          parent: "t",
          inputs: {
            OPERAND1: [3, "cw", [10, ""]],
            OPERAND2: [1, [10, "-360"]],
          },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        cw: {
          opcode: "operator_subtract",
          next: null,
          parent: "bn",
          inputs: {
            NUM1: [3, [12, "clone y", "(mJi~`u5kn]QxBOc,Bj9"], [4, ""]],
            NUM2: [3, [12, "camera y", ";sLdt+zV]./UgHiZH2)+"], [4, ""]],
          },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        cv: {
          opcode: "data_changevariableby",
          next: null,
          parent: "t",
          inputs: { VALUE: [1, [4, "720"]] },
          fields: { VARIABLE: ["clone y", "(mJi~`u5kn]QxBOc,Bj9"] },
          shadow: false,
          topLevel: false,
        },
        T: {
          opcode: "looks_switchcostumeto",
          next: "u",
          parent: "t",
          inputs: { COSTUME: [1, "cx"] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        cx: {
          opcode: "looks_costume",
          next: null,
          parent: "T",
          inputs: {},
          fields: { COSTUME: ["move", null] },
          shadow: true,
          topLevel: false,
        },
        u: {
          opcode: "motion_gotoxy",
          next: "U",
          parent: "T",
          inputs: { X: [3, "cy", [4, ""]], Y: [3, "cz", [4, ""]] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        cy: {
          opcode: "operator_subtract",
          next: null,
          parent: "u",
          inputs: {
            NUM1: [3, [12, "clone x", "29zCYncZ6{;WJ.7N4k8B"], [4, ""]],
            NUM2: [3, [12, "camera x", "+qm~UdN|JU.$.!V$*+Ka"], [4, ""]],
          },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        cz: {
          opcode: "operator_subtract",
          next: null,
          parent: "u",
          inputs: {
            NUM1: [3, [12, "clone y", "(mJi~`u5kn]QxBOc,Bj9"], [4, ""]],
            NUM2: [3, [12, "camera y", ";sLdt+zV]./UgHiZH2)+"], [4, ""]],
          },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        U: {
          opcode: "looks_switchcostumeto",
          next: "V",
          parent: "u",
          inputs: { COSTUME: [1, "cA"] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        cA: {
          opcode: "looks_costume",
          next: null,
          parent: "U",
          inputs: {},
          fields: { COSTUME: ["Nothing", null] },
          shadow: true,
          topLevel: false,
        },
        V: {
          opcode: "looks_switchcostumeto",
          next: null,
          parent: "U",
          inputs: { COSTUME: [3, "bo", "cB"] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        bo: {
          opcode: "operator_join",
          next: null,
          parent: "V",
          inputs: {
            STRING1: [3, "cC", [10, ""]],
            STRING2: [3, [12, "clone y", "(mJi~`u5kn]QxBOc,Bj9"], [10, ""]],
          },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        cC: {
          opcode: "operator_join",
          next: null,
          parent: "bo",
          inputs: {
            STRING1: [3, [12, "clone x", "29zCYncZ6{;WJ.7N4k8B"], [10, ""]],
            STRING2: [1, [10, ","]],
          },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        cB: {
          opcode: "looks_costume",
          next: null,
          parent: "V",
          inputs: {},
          fields: { COSTUME: ["0,0", null] },
          shadow: true,
          topLevel: false,
        },
      },
      comments: {},
      currentCostume: 0,
      costumes: [
        {
          name: "Nothing",
          bitmapResolution: 1,
          dataFormat: "svg",
          assetId: "cd21514d0531fdffb22204e0ec5ed84a",
          md5ext: "cd21514d0531fdffb22204e0ec5ed84a.svg",
          rotationCenterX: 0,
          rotationCenterY: 0,
        },
        {
          name: "move",
          bitmapResolution: 1,
          dataFormat: "svg",
          assetId: "8366d3f8863b6589493be6afe22408e2",
          md5ext: "8366d3f8863b6589493be6afe22408e2.svg",
          rotationCenterX: 270.5,
          rotationCenterY: 203,
        },
      ],
      sounds: [],
      volume: 100,
      layerOrder: 1,
      visible: false,
      x: 0,
      y: 0,
      size: 100,
      direction: 90,
      draggable: false,
      rotationStyle: "all around",
    },
    {
      isStage: false,
      name: "camera",
      variables: {},
      lists: {},
      broadcasts: {},
      blocks: {
        cD: {
          opcode: "event_whenflagclicked",
          next: "bp",
          parent: null,
          inputs: {},
          fields: {},
          shadow: false,
          topLevel: true,
          x: 346,
          y: 281,
        },
        bp: {
          opcode: "data_setvariableto",
          next: "bq",
          parent: "cD",
          inputs: { VALUE: [1, [10, "0"]] },
          fields: { VARIABLE: ["camera x", "+qm~UdN|JU.$.!V$*+Ka"] },
          shadow: false,
          topLevel: false,
        },
        bq: {
          opcode: "data_setvariableto",
          next: "br",
          parent: "bp",
          inputs: { VALUE: [1, [10, "0"]] },
          fields: { VARIABLE: ["camera y", ";sLdt+zV]./UgHiZH2)+"] },
          shadow: false,
          topLevel: false,
        },
        br: {
          opcode: "control_forever",
          next: null,
          parent: "bq",
          inputs: { SUBSTACK: [2, "W"] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        W: {
          opcode: "data_changevariableby",
          next: "bs",
          parent: "br",
          inputs: { VALUE: [3, "bt", [4, ""]] },
          fields: { VARIABLE: ["camera x", "+qm~UdN|JU.$.!V$*+Ka"] },
          shadow: false,
          topLevel: false,
        },
        bt: {
          opcode: "operator_multiply",
          next: null,
          parent: "W",
          inputs: { NUM1: [3, "cE", [4, ""]], NUM2: [1, [4, "0.2"]] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        cE: {
          opcode: "operator_subtract",
          next: null,
          parent: "bt",
          inputs: {
            NUM1: [3, [12, "player x", "Omb^c,YW;.!Uj1A7~oJ1"], [4, ""]],
            NUM2: [3, [12, "camera x", "+qm~UdN|JU.$.!V$*+Ka"], [4, ""]],
          },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        bs: {
          opcode: "data_changevariableby",
          next: null,
          parent: "W",
          inputs: { VALUE: [3, "bu", [4, ""]] },
          fields: { VARIABLE: ["camera y", ";sLdt+zV]./UgHiZH2)+"] },
          shadow: false,
          topLevel: false,
        },
        bu: {
          opcode: "operator_multiply",
          next: null,
          parent: "bs",
          inputs: { NUM1: [3, "cF", [4, ""]], NUM2: [1, [4, "0.2"]] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        cF: {
          opcode: "operator_subtract",
          next: null,
          parent: "bu",
          inputs: {
            NUM1: [3, [12, "player y", "e[7yT@wnA!3^S:!PNY~Q"], [4, ""]],
            NUM2: [3, [12, "camera y", ";sLdt+zV]./UgHiZH2)+"], [4, ""]],
          },
          fields: {},
          shadow: false,
          topLevel: false,
        },
      },
      comments: {},
      currentCostume: 0,
      costumes: [
        {
          name: "Nothing",
          bitmapResolution: 1,
          dataFormat: "svg",
          assetId: "cd21514d0531fdffb22204e0ec5ed84a",
          md5ext: "cd21514d0531fdffb22204e0ec5ed84a.svg",
          rotationCenterX: 0,
          rotationCenterY: 0,
        },
      ],
      sounds: [],
      volume: 100,
      layerOrder: 3,
      visible: true,
      x: 0,
      y: 0,
      size: 100,
      direction: 90,
      draggable: false,
      rotationStyle: "all around",
    },
  ],
  monitors: [
    {
      id: "/]:RR9WxA|~;a{XK,{rv",
      mode: "list",
      opcode: "data_listcontents",
      params: { LIST: "world data" },
      spriteName: null,
      value: [],
      width: 0,
      height: 0,
      x: 6,
      y: 58,
      visible: false,
    },
    {
      id: "Omb^c,YW;.!Uj1A7~oJ1",
      mode: "default",
      opcode: "data_variable",
      params: { VARIABLE: "player x" },
      spriteName: null,
      value: 0,
      width: 0,
      height: 0,
      x: 0,
      y: 173,
      visible: false,
      sliderMin: 0,
      sliderMax: 100,
      isDiscrete: true,
    },
    {
      id: "e[7yT@wnA!3^S:!PNY~Q",
      mode: "default",
      opcode: "data_variable",
      params: { VARIABLE: "player y" },
      spriteName: null,
      value: 0,
      width: 0,
      height: 0,
      x: 5,
      y: 32,
      visible: false,
      sliderMin: 0,
      sliderMax: 100,
      isDiscrete: true,
    },
    {
      id: "+qm~UdN|JU.$.!V$*+Ka",
      mode: "default",
      opcode: "data_variable",
      params: { VARIABLE: "camera x" },
      spriteName: null,
      value: 0,
      width: 0,
      height: 0,
      x: 0,
      y: 140,
      visible: false,
      sliderMin: 0,
      sliderMax: 100,
      isDiscrete: true,
    },
    {
      id: ";sLdt+zV]./UgHiZH2)+",
      mode: "default",
      opcode: "data_variable",
      params: { VARIABLE: "camera y" },
      spriteName: null,
      value: 0,
      width: 0,
      height: 0,
      x: 5,
      y: 32,
      visible: false,
      sliderMin: 0,
      sliderMax: 100,
      isDiscrete: true,
    },
    {
      id: "$/yw+8k;*81pDO7cl%%P",
      mode: "default",
      opcode: "data_variable",
      params: { VARIABLE: "speed x" },
      spriteName: null,
      value: 0,
      width: 0,
      height: 0,
      x: 0,
      y: 109,
      visible: false,
      sliderMin: 0,
      sliderMax: 100,
      isDiscrete: true,
    },
    {
      id: "pT.e}n4RtL+`ZAiT$cnI",
      mode: "default",
      opcode: "data_variable",
      params: { VARIABLE: "speed y" },
      spriteName: null,
      value: 0,
      width: 0,
      height: 0,
      x: 5,
      y: 32,
      visible: false,
      sliderMin: 0,
      sliderMax: 100,
      isDiscrete: true,
    },
    {
      id: "29zCYncZ6{;WJ.7N4k8B",
      mode: "default",
      opcode: "data_variable",
      params: { VARIABLE: "clone x" },
      spriteName: "world",
      value: 0,
      width: 0,
      height: 0,
      x: 0,
      y: 74,
      visible: false,
      sliderMin: 0,
      sliderMax: 100,
      isDiscrete: true,
    },
    {
      id: "(mJi~`u5kn]QxBOc,Bj9",
      mode: "default",
      opcode: "data_variable",
      params: { VARIABLE: "clone y" },
      spriteName: "world",
      value: 0,
      width: 0,
      height: 0,
      x: 5,
      y: 32,
      visible: false,
      sliderMin: 0,
      sliderMax: 100,
      isDiscrete: true,
    },
  ],
  extensions: [],
  meta: {
    semver: "3.0.0",
    vm: "0.2.0",
    agent: "",
    platform: { name: "TurboWarp", url: "https://turbowarp.org/" },
  },
};

export default projectJson;
